name: Deploy Infrastructure

on:
  push:
    branches:
      - iac-terraform

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'CloudGalleryApi/**'

      - if: steps.filter.outputs.src == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - if: steps.filter.outputs.src == 'true'
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
        
      - if: steps.filter.outputs.src == 'true'
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/felhoalapu-lab-hf1/cloud-lab-be:latest ./CloudGalleryApi
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/felhoalapu-lab-hf1/cloud-lab-be:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - 'cloud-gallery-fe/**'

      - if: steps.filter.outputs.src == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - if: steps.filter.outputs.src == 'true'
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
        
      - if: steps.filter.outputs.src == 'true'
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/felhoalapu-lab-hf1/cloud-lab-fe:latest ./cloud-gallery-fe
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/felhoalapu-lab-hf1/cloud-lab-fe:latest


  terraform-deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
        working-directory: ./terraform
      - run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}"
        working-directory: ./terraform